mod database './justfiles/database.just'
mod cache './justfiles/cache.just'
mod scrape './justfiles/scrape.just'
mod postgres './justfiles/postgres.just'

# List everything
default:
    @just --list

# Set-up local instance of Plum
set-up-local-dev:
    @just database::start-database
    @just cache::start-cache
    @just postgres::start-postgres
    @sleep 1
    @bun ./seed/seed.ts
    @just scrape::all
    @bun run dev